[theme]
primaryColor = "#087e8b"
backgroundColor = "#f6f8fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#163944"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
